[package]
name = "nxplorer"
version = "1.2.5"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
glob = "0.3.2"
ratatui = "0.29.0"
serde_json = "1.0.140"
tui-textarea = "*"
fuzzy-matcher = "0.3.7"

[profile.release]
codegen-units = 1
strip = true
lto = true
