[package]
name = "nxplorer"
version = "1.1.3"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
glob = "0.3.1"
ratatui = "0.29.0"
serde_json = "1.0.133"
tui-textarea = "*"
regex = {version = "1.11.1", default-features = false}

[profile.release]
opt-level = "s"
codegen-units = 1
lto = true
